/* Convite editável por perfil de casamento, com publicação explícita. */
Object.assign(state,{invitation:null,invitationError:false});
if(!navItems.some(x=>x[0]==='convite'))navItems.splice(navItems.findIndex(x=>x[0]==='manual-convidado')+1,0,['convite','Convite digital','heart']);
const invitationReset=resetWeddingCollections;
resetWeddingCollections=function(){invitationReset();state.invitation=null;state.invitationError=false;};
const invitationLoad=loadWeddingData;
loadWeddingData=async function(id){await invitationLoad(id);state.invitation=null;state.invitationError=false;if(!id)return;const r=await sb.from('wedding_invitations').select('*').eq('wedding_id',id).maybeSingle();state.invitation=r.data;state.invitationError=!!r.error;};
function invitationUrl(){if(!state.wedding?.rsvp_code)return '';const page=state.invitation?.content?.share_page;const u=new URL(/^convite-[a-z0-9-]+\.html$/.test(page||'')?page:'convite.html',location.href);u.search='';u.hash='';u.searchParams.set('code',state.wedding.rsvp_code);return u.href;}
function invitationView(){const c={...AMSInvitation.defaults(state.wedding),...state.invitation?.content};return `<div class="page guest-page"><div class="page-head"><div><h1>Convite digital</h1><p>Capa com abertura, convite personalizado e música para este casal.</p></div><div class="guest-actions"><button class="btn-secondary" id="invitation-copy">Copiar link</button><button class="btn-secondary" id="invitation-open">Ver página publicada</button></div></div>
 ${state.invitationError?'<p role="alert">Não foi possível carregar o convite. Reabra a seção antes de editar.</p>':''}
 <div class="card card-pad"><strong>${state.invitation?.published?'Convite publicado':'Convite não publicado'}</strong><p>Edite os campos, confira a prévia e salve. Cada perfil tem seu próprio convite.</p><input class="input" aria-label="Link do convite" readonly value="${esc(invitationUrl())}"></div>
 <form id="invitation-form" class="card card-pad" style="margin-top:20px">
 <div class="invitation-editor-grid">${AMSInvitation.fields.map(([key,label,type])=>`<div class="field ${type==='textarea'?'wide':''}"><label for="invitation-${key}">${label}</label>${type==='textarea'?`<textarea class="input" id="invitation-${key}" name="${key}" maxlength="5000">${esc(c[key]||'')}</textarea>`:`<input class="input" id="invitation-${key}" name="${key}" type="${type==='image'?'text':type}" ${type==='number'?'min="0" max="100"':type==='color'?'':'maxlength="2000"'} value="${esc(type==='url'&&c[key]?AMSInvitation.url(c[key]):c[key]??'')}">`}</div>`).join('')}</div>
 <section class="invitation-editor-section"><h2>Enviar imagens e música</h2><p class="small muted">Os arquivos enviados serão visíveis para quem receber o convite. Depois do upload, clique em Salvar convite.</p>
 <div class="invitation-editor-grid"><div class="field"><label for="invitation-photo-upload">Enviar foto do casal</label><input id="invitation-photo-upload" type="file" accept="image/jpeg,image/png,image/webp" data-invitation-upload="photo_url"></div><div class="field"><label for="invitation-cover-upload">Enviar imagem da capa</label><input id="invitation-cover-upload" type="file" accept="image/jpeg,image/png,image/webp" data-invitation-upload="cover_url"></div><div class="field wide"><label for="invitation-music-upload">Enviar música (MP3, M4A, OGG ou WAV, até 15 MB)</label><input id="invitation-music-upload" type="file" accept="audio/mpeg,audio/mp4,audio/ogg,audio/wav,audio/x-wav,audio/webm,audio/aac,.mp3,.m4a,.ogg,.wav,.aac" data-invitation-upload="music_url"></div></div>
 <p id="invitation-upload-status" role="status"></p>
 <label class="guest-checkbox"><input type="checkbox" name="music_enabled" ${c.music_enabled?'checked':''}> Tocar música ao abrir o envelope</label>
 <label class="guest-checkbox"><input type="checkbox" name="music_loop" ${c.music_loop!==false?'checked':''}> Repetir música</label><p class="small muted">A música começa ao tocar na capa. O convidado pode pausar a qualquer momento.</p></section>
 <section class="invitation-editor-section"><label class="guest-checkbox"><input type="checkbox" name="published" ${state.invitation?.published?'checked':''}> Publicar convite para quem receber o link</label><div class="guest-actions" style="margin-top:18px"><button type="button" class="btn-secondary" id="invitation-preview">Prévia das alterações</button><button class="btn-primary" type="submit" ${state.invitationError?'disabled':''}>Salvar convite</button></div><p id="invitation-save-status" role="status"></p></section></form></div>`;}
const invitationBaseView=viewFor;
viewFor=function(r){return r==='convite'&&state.wedding?invitationView():invitationBaseView(r);};
function invitationReadForm(form){const values=Object.fromEntries(new FormData(form)),content={};for(const [key,,type] of AMSInvitation.fields){const v=String(values[key]||'').trim();if(type==='url'&&v&&!AMSInvitation.url(v))throw new Error('Confira os links. Use endereços que começam com https://.');if(type==='image'&&v&&!AMSInvitation.url(v,true))throw new Error('Confira o link da foto.');content[key]=type==='number'?Number(v):v;}if(!content.partner1||!content.partner2)throw new Error('Informe os nomes do casal.');content.music_enabled=form.elements.music_enabled.checked;content.music_loop=form.elements.music_loop.checked;return content;}
const invitationBaseBind=bindView;
bindView=function(r){invitationBaseBind(r);if(r!=='convite')return;const form=document.getElementById('invitation-form'),weddingId=state.wedding.id;let uploading=false;
 document.getElementById('invitation-copy').onclick=async()=>{const url=invitationUrl();if(!url)return;try{await navigator.clipboard.writeText(url);toast('Link do convite copiado.');}catch{window.prompt('Copie o link do convite:',url);}};
 document.getElementById('invitation-open').onclick=()=>{if(invitationUrl())window.open(invitationUrl(),'_blank','noopener');};
 document.querySelectorAll('[data-invitation-upload]').forEach(input=>input.onchange=async()=>{
  const file=input.files?.[0];if(!file)return;const field=input.dataset.invitationUpload,status=document.getElementById('invitation-upload-status');
  const mime=file.type||({mp3:'audio/mpeg',m4a:'audio/mp4',ogg:'audio/ogg',wav:'audio/wav',aac:'audio/aac'}[file.name.split('.').pop().toLowerCase()]);
  const allowed=field==='music_url'?['audio/mpeg','audio/mp4','audio/ogg','audio/wav','audio/x-wav','audio/webm','audio/aac']:['image/jpeg','image/png','image/webp'];
  if(file.size>15*1024*1024||!allowed.includes(mime)){status.textContent='Escolha um arquivo do formato indicado com até 15 MB.';input.value='';return;}
  uploading=true;form.querySelectorAll('button,input[type=file]').forEach(b=>b.disabled=true);status.textContent='Enviando arquivo…';
  const extension=({ 'audio/mpeg':'mp3','audio/mp4':'m4a','audio/ogg':'ogg','audio/wav':'wav','audio/x-wav':'wav','audio/webm':'webm','audio/aac':'aac','image/jpeg':'jpg','image/png':'png','image/webp':'webp'})[mime];
  const path=`${weddingId}/${field}-${crypto.randomUUID()}.${extension}`;
  try{const {error}=await sb.storage.from('invitation-media').upload(path,file,{contentType:mime,upsert:false});if(error)throw error;const {data}=sb.storage.from('invitation-media').getPublicUrl(path);form.elements[field].value=data.publicUrl;if(field==='music_url')form.elements.music_enabled.checked=true;status.textContent='Arquivo enviado. Clique em Salvar convite para aplicar.';}
  catch(error){console.error(error);status.textContent='Não foi possível enviar. Tente novamente.';}
  finally{uploading=false;form.querySelectorAll('button,input[type=file]').forEach(b=>b.disabled=false);}
 });
 document.getElementById('invitation-preview').onclick=()=>{try{const content=invitationReadForm(form),dialog=document.createElement('div');dialog.className='invitation-preview-dialog';dialog.setAttribute('role','dialog');dialog.setAttribute('aria-modal','true');dialog.setAttribute('aria-label','Prévia do convite');dialog.innerHTML='<button class="invitation-preview-close">Fechar prévia</button>'+AMSInvitation.render(content,{gifts:giftPublicUrl(),manual:manualUrl(),rsvp:state.wedding.guest_registration_code?guestRegistrationUrl():guestRsvpUrl()});document.body.appendChild(dialog);const close=()=>{dialog.remove();document.removeEventListener('keydown',key);document.getElementById('invitation-preview')?.focus();};const key=e=>{if(e.key==='Escape')close();};dialog.querySelector('.invitation-preview-close').onclick=close;document.addEventListener('keydown',key);AMSInvitation.bindOpen(dialog);dialog.querySelector('.invitation-preview-close').focus();}catch(error){toast(error.message);}};
 form.onsubmit=async e=>{e.preventDefault();if(uploading)return;const button=form.querySelector('[type=submit]');try{const content=invitationReadForm(form);button.disabled=true;const {error}=await sb.from('wedding_invitations').upsert({wedding_id:weddingId,content:{...state.invitation?.content,...content},published:form.elements.published.checked,updated_at:new Date().toISOString()});if(error)throw error;if(state.wedding?.id===weddingId){await loadWeddingData(weddingId);render();}toast('Convite salvo.');}catch(error){console.error(error);document.getElementById('invitation-save-status').textContent=error.message||'Não foi possível salvar.';button.disabled=false;}};
};
