/* Lista de presentes por casamento — administração e acesso público separados. */
Object.assign(state,{gifts:[],giftSettings:null,giftError:false});
if(!navItems.some(([key])=>key==='presentes')) navItems.splice(navItems.findIndex(([key])=>key==='convidados')+1,0,['presentes','Lista de presentes','heart']);
const giftBaseReset=resetWeddingCollections;
resetWeddingCollections=function(){giftBaseReset();state.gifts=[];state.giftSettings=null;state.giftError=false;};
const giftBaseLoad=loadWeddingData;
loadWeddingData=async function(id){
  await giftBaseLoad(id);state.gifts=[];state.giftSettings=null;state.giftError=false;if(!id)return;
  const results=await Promise.all([sb.from('wedding_gifts').select('*').eq('wedding_id',id).order('created_at'),sb.from('wedding_gift_settings').select('*').eq('wedding_id',id).maybeSingle()]);
  state.giftError=results.some(r=>r.error);state.gifts=results[0].data||[];state.giftSettings=results[1].data;
};
function giftPublicUrl(){if(!state.wedding?.rsvp_code)return '';const u=new URL('presentes.html',location.href);u.search='';u.hash='';u.searchParams.set('code',state.wedding.rsvp_code);return u.toString();}
function giftMoney(value){return Number(value).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});}
function giftListView(){const s=state.giftSettings;return `<div class="page guest-page"><div class="page-head guest-page-head"><div><h1>Lista de presentes</h1><p>Presentes simbólicos com contribuições por Pix diretamente para os noivos.</p></div><div class="guest-actions"><button class="btn-secondary" id="gift-settings">Configurar Pix</button><button class="btn-secondary" id="copy-gift-link">Copiar link</button><button class="btn-secondary" id="open-gift-link">Ver página</button><button class="btn-primary" id="new-gift">+ Presente</button></div></div>${state.giftError?'<div class="card card-pad">Não foi possível carregar a lista de presentes. Tente novamente.</div>':''}<div class="card card-pad"><strong>${s?.published?'Página publicada':'Página não publicada'}</strong><p class="small muted">${s?.published?'A chave Pix e o nome do favorecido ficam visíveis para quem recebe o link.':'Configure o Pix e habilite a página quando estiver pronta para compartilhar.'}</p>${s?`<p>${esc(s.recipient_name)} • ${esc(s.pix_key)}</p>`:''}<div class="guest-public-link">${esc(giftPublicUrl())}</div></div><div class="card list-card" style="margin-top:20px">${state.gifts.length?state.gifts.map(g=>`<div class="list-row"><div class="vendor-name"><strong>${esc(g.name)}</strong><span>${esc(g.description||'Presente simbólico')}</span></div><strong>${giftMoney(g.amount)}</strong><span class="badge ${g.active?'success':'warning'}">${g.active?'Visível':'Oculto'}</span><button class="btn-secondary" data-edit-gift="${g.id}">Editar</button></div>`).join(''):emptyState('Sua lista está vazia','Cadastre os presentes que os convidados poderão escolher.')}</div><p class="small muted">As transferências são feitas no aplicativo do banco. Confira os recebimentos na conta dos noivos.</p></div>`;}
const giftBaseView=viewFor;
viewFor=function(r){return r==='presentes'&&state.wedding?giftListView():giftBaseView(r);};
function openGiftSettings(){const s=state.giftSettings;modal('Configurar Pix',field('Chave Pix','pix_key',s?.pix_key||'','text','required maxlength="140"')+field('Nome do favorecido (como aparece no banco)','recipient_name',s?.recipient_name||'','text','required maxlength="120"')+`<label class="guest-checkbox"><input type="checkbox" name="published" ${s?.published?'checked':''}> Publicar página e dados Pix para quem recebe o link</label>`, 'Salvar',async el=>{const form=el.querySelector('.modal'),f=Object.fromEntries(new FormData(form));const payload={wedding_id:state.wedding.id,pix_key:f.pix_key.trim(),recipient_name:f.recipient_name.trim(),published:form.querySelector('[name=published]').checked};if(!payload.pix_key||!payload.recipient_name){toast('Informe a chave Pix e o favorecido.');return false;}const {error}=await sb.from('wedding_gift_settings').upsert(payload);if(error){toast('Não foi possível salvar o Pix.');return false;}await loadWeddingData(state.wedding.id);render();toast('Pix atualizado.');return true;});}
function openGiftEditor(g){const back=modal(g?'Editar presente':'Novo presente',field('Nome do presente','name',g?.name||'','text','required maxlength="120"')+field('Valor sugerido (R$)','amount',g?.amount||'','number','required min="0.01" max="999999.99" step="0.01"')+`<div class="field"><label>Descrição</label><textarea class="input" name="description" maxlength="1000">${esc(g?.description||'')}</textarea></div><label class="guest-checkbox"><input type="checkbox" name="active" ${g?.active!==false?'checked':''}> Exibir na página pública</label>`,'Salvar',async el=>{const form=el.querySelector('.modal'),f=Object.fromEntries(new FormData(form));const p={wedding_id:state.wedding.id,name:f.name.trim(),description:f.description.trim(),amount:Number(f.amount),active:form.querySelector('[name=active]').checked};if(!p.name||!Number.isFinite(p.amount)||p.amount<=0||p.amount>999999.99){toast('Informe nome e valor válido.');return false;}const {error}=await(g?sb.from('wedding_gifts').update(p).eq('id',g.id).eq('wedding_id',state.wedding.id):sb.from('wedding_gifts').insert(p));if(error){toast('Não foi possível salvar o presente.');return false;}await loadWeddingData(state.wedding.id);render();toast('Presente salvo.');return true;});if(g){const b=document.createElement('button');b.type='button';b.className='btn-secondary';b.textContent='Remover';b.onclick=async()=>{if(!confirm('Remover este presente?'))return;const {error}=await sb.from('wedding_gifts').delete().eq('id',g.id).eq('wedding_id',state.wedding.id);if(error){toast('Não foi possível remover.');return;}back.remove();await loadWeddingData(state.wedding.id);render();};back.querySelector('.modal-actions').prepend(b);}}
const giftBaseBind=bindView;
bindView=function(r){giftBaseBind(r);const on=(id,fn)=>{const el=document.getElementById(id);if(el)el.onclick=fn;};on('gift-settings',openGiftSettings);on('new-gift',()=>openGiftEditor(null));on('open-gift-link',()=>{const url=giftPublicUrl();if(url)window.open(url,'_blank','noopener');});on('copy-gift-link',async()=>{try{const url=giftPublicUrl();if(!url){toast('Link indisponível.');return;}await navigator.clipboard.writeText(url);toast('Link copiado.');}catch{toast('Copie o link exibido na página.');}});document.querySelectorAll('[data-edit-gift]').forEach(b=>b.onclick=()=>openGiftEditor(state.gifts.find(g=>g.id===b.dataset.editGift)));};
